// design/midad/tokens.json  →  the Awzan design-system token layer.
//
// WHY THIS IS GENERATED AND NOT TYPED. The design system is itself generated by
// a toolchain that does not live in this repo (product-spec/reference/
// design-system.md § Hand-edits), so `tokens.json` is the only durable link
// between the design and the app. Twenty colours × two themes and fifteen type
// styles transcribed by hand is forty-odd hex values and sixty numbers, and a
// single wrong digit in `#e0d8ca` is invisible in review and wrong on every
// screen. Re-run this instead.
//
//   node ios/tools/generate-tokens.mjs
//
// The OUTPUT is committed and meant to be read — this is a one-shot generator,
// not a build step. Nothing in the Xcode build runs it.
//
// What it does NOT own: TypeStyle.swift, which resolves a style to a real font
// and applies its line height. That is logic, and it is hand-written beside the
// data this file emits.

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const TOKENS = JSON.parse(readFileSync(join(REPO, 'design/midad/tokens.json'), 'utf8'));
const APP = join(REPO, 'ios/Awzan');
const ASSETS = join(APP, 'Resources/Assets.xcassets');
const OUT = join(APP, 'DesignSystem/Tokens');

const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const px = (v) => Number(String(v).replace('px', ''));
const banner = (what) => `// GENERATED by ios/tools/generate-tokens.mjs from design/midad/tokens.json.
// ${what}
// Do not edit by hand — re-run the generator. Design system version ${TOKENS.version}.
`;

// ---------------------------------------------------------------- colours ---
// A colour set per token, each carrying both themes. Night is an APPEARANCE on
// one asset rather than a second palette the app switches between, so a view
// that reads Midad.ink is correct in both without knowing a theme exists —
// which is what "never hard-code a colour" is actually protecting.
function colorComponents(hex) {
  const h = hex.replace('#', '');
  const p = h.length === 3 ? h.split('').map((c) => c + c) : h.match(/../g);
  return {
    red: `0x${p[0].toUpperCase()}`,
    green: `0x${p[1].toUpperCase()}`,
    blue: `0x${p[2].toUpperCase()}`,
    alpha: p[3] ? (parseInt(p[3], 16) / 255).toFixed(3) : '1.000',
  };
}

function writeColors() {
  if (existsSync(join(ASSETS, 'Colors'))) rmSync(join(ASSETS, 'Colors'), { recursive: true });
  mkdirSync(join(ASSETS, 'Colors'), { recursive: true });
  writeFileSync(join(ASSETS, 'Contents.json'),
    JSON.stringify({ info: { author: 'xcode', version: 1 } }, null, 2) + '\n');
  writeFileSync(join(ASSETS, 'Colors/Contents.json'),
    JSON.stringify({ info: { author: 'xcode', version: 1 }, properties: { 'provides-namespace': false } }, null, 2) + '\n');

  const lines = [];
  for (const t of TOKENS.color.tokens) {
    const name = camel(t.name);
    const dir = join(ASSETS, 'Colors', `${name}.colorset`);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'Contents.json'), JSON.stringify({
      colors: [
        { color: { 'color-space': 'srgb', components: colorComponents(t.value.midad) }, idiom: 'universal' },
        {
          appearances: [{ appearance: 'luminosity', value: 'dark' }],
          color: { 'color-space': 'srgb', components: colorComponents(t.value['midad-night']) },
          idiom: 'universal',
        },
      ],
      info: { author: 'xcode', version: 1 },
    }, null, 2) + '\n');

    lines.push(`    /// ${t.usage}`);
    lines.push(`    ///`);
    lines.push(`    /// Paper \`${t.value.midad}\` · Night \`${t.value['midad-night']}\``);
    lines.push(`    public static let ${name} = Color(.${name})`);
    lines.push('');
  }

  const header = [
    banner('The twenty semantic colours, as one namespace over Assets.xcassets/Colors.'),
    'import SwiftUI',
    '',
    '/// The Midād palette — ink on paper, and one rubric red.',
    '///',
    '/// **Two channels that never cross** (product-spec D-58, rule 3): `sign` marks',
    '/// the letters that carry the grammar and never fills a box; `correct` and',
    "/// `wrong` colour an option's fill, border, mark and word and never a letter.",
    '/// Success leans teal so it never pairs with `wrong` on the red–green axis,',
    '/// and every verdict carries an icon and a word besides its colour.',
    '///',
    '/// Namespaced rather than hung off `Color` because several token names —',
    "/// `fill`, `line`, `background` — already exist on SwiftUI's `ShapeStyle`,",
    '/// where a bare `.fill` would resolve to the wrong one. The prefix also makes',
    '/// the D1 exit criterion greppable: a colour anywhere downstream that is not',
    '/// `Midad.something` is a hard-coded colour.',
    '///',
    '/// Night is an *appearance* inside each colour set, not a second palette, so',
    '/// nothing that reads a token has to know which theme is showing.',
    'public enum Midad {',
    '',
  ].join('\n');
  writeFileSync(join(OUT, 'MidadColor.swift'), header + lines.join('\n') + '}\n');
  return TOKENS.color.tokens.length;
}

// ------------------------------------------------------------------- type ---
// Which Dynamic Type ramp each style scales against is a PORT decision, not
// design data: the web has no Dynamic Type, so tokens.json has nothing to say
// about it. Written out here, beside the sizes, so the pairing can be read in
// one place and argued with.
const RAMP = {
  'arabic-hero': 'largeTitle', 'arabic-display': 'title', 'arabic-title': 'title2',
  'arabic-cell': 'title3', 'arabic-body': 'body', 'arabic-label': 'subheadline',
  'screen-title': 'largeTitle', 'meaning-display': 'title2', 'reading': 'subheadline',
  'gloss': 'callout',
  'headline': 'headline', 'verdict': 'title3', 'body': 'body', 'label': 'footnote',
  'caption': 'caption', 'numeral': 'title',
};

function writeType() {
  const out = [];
  let count = 0;
  for (const group of TOKENS.type.groups) {
    out.push(`    // MARK: - ${group.name}`);
    out.push(`    //`);
    for (const line of group.note.match(/.{1,74}(\s|$)/g)) out.push(`    // ${line.trim()}`);
    out.push('');
    for (const s of group.styles) {
      const name = camel(s.name);
      const ramp = RAMP[s.name];
      if (!ramp) throw new Error(`no Dynamic Type ramp declared for "${s.name}"`);
      out.push(`    /// ${s.usage}`);
      out.push(`    ///`);
      out.push(`    /// \`${px(s.fontSize)} / ${px(s.lineHeight)}\`${s.fontWeight !== 400 ? `, weight ${s.fontWeight}` : ''}${s.fontStyle === 'italic' ? ', italic' : ''} — e.g. ${s.sample}`);
      out.push(`    static let ${name} = TypeStyle(`);
      out.push(`        face: .${group.family},`);
      out.push(`        size: ${px(s.fontSize)},`);
      out.push(`        lineHeight: ${px(s.lineHeight)},`);
      out.push(`        weight: ${s.fontWeight},`);
      out.push(`        italic: ${s.fontStyle === 'italic'},`);
      out.push(`        tracking: ${s.letterSpacing ? Number(String(s.letterSpacing).replace('em', '')) : 0},`);
      out.push(`        ramp: .${ramp}${s.name === 'numeral' ? ',\n        tabularFigures: true' : ''}`);
      out.push(`    )`);
      out.push('');
      count++;
    }
  }
  const header = [
    banner('The type scale. TypeStyle itself — how a style becomes a font — is hand-written next door.'),
    'import SwiftUI',
    '',
    '/// The Midād type scale: **three voices, three faces** (product-spec D-59).',
    '///',
    '/// Arabic (`arabic*`) is the object of study, the serif italic is a *meaning*,',
    '/// the sans is the interface talking. Nothing else gets a face.',
    '///',
    '/// Every style carries an explicit `lineHeight`, which is the whole point:',
    "/// vowelled Arabic is taller than a font's nominal line box and a shadda over a",
    '/// ḍamma stacks two marks, so Scheherazade’s own metrics are not enough. D-59',
    '/// obliges explicit row heights rather than fighting them — see `TypeStyle`.',
    'public extension TypeStyle {',
    '',
  ].join('\n');
  writeFileSync(join(OUT, 'MidadType.swift'), header + out.join('\n') + '}\n');
  return count;
}

// ---------------------------------------------------------------- metrics ---
function writeMetrics() {
  const section = (title, note, tokens, kind) => {
    const rows = [];
    rows.push(`    // MARK: - ${title}`);
    rows.push(`    //`);
    for (const line of note.match(/.{1,74}(\s|$)/g)) rows.push(`    // ${line.trim()}`);
    rows.push('');
    for (const t of tokens) {
      const name = camel(t.name.replace(/^(space|radius)-/, ''));
      rows.push(`    /// ${t.usage}`);
      // An empty `kind` means the token's own name already reads as one
      // (`tapTarget`); prefixing would capitalise it into `TapTarget`.
      const swift = kind ? `${kind}${name[0].toUpperCase()}${name.slice(1)}` : name;
      rows.push(`    static let ${swift}: CGFloat = ${px(t.value)}`);
      rows.push('');
    }
    return rows.join('\n');
  };

  const header = [
    banner('Spacing, corner radii and the fixed sizes.'),
    'import CoreGraphics',
    '',
    '/// The measurements the design fixes: a 4-point spacing base, five radii, and',
    '/// the three heights that are not negotiable.',
    '///',
    '/// `radiusFull` is deliberately absent. On the web it is `9999px`; in SwiftUI a',
    '/// fully-rounded end is `Capsule()`, a different shape rather than a large',
    '/// number, and the design allows it for read-only pills only.',
    'public extension Midad {',
    '',
  ].join('\n');
  writeFileSync(join(OUT, 'MidadMetrics.swift'), header
    + section('Spacing', TOKENS.spacing.note, TOKENS.spacing.tokens, 'space') + '\n'
    + section('Radii', TOKENS.radius.note, TOKENS.radius.tokens.filter((t) => t.name !== 'radius-full'), 'radius') + '\n'
    + section('Fixed sizes', TOKENS.size.note, TOKENS.size.tokens, '') + '}\n');
  return TOKENS.spacing.tokens.length + TOKENS.radius.tokens.length - 1 + TOKENS.size.tokens.length;
}

mkdirSync(OUT, { recursive: true });
console.log(`colours   ${writeColors()}`);
console.log(`type      ${writeType()}`);
console.log(`metrics   ${writeMetrics()}`);
