// GENERATED by ios/tools/generate-tokens.mjs from design/midad/tokens.json.
// Spacing, corner radii and the fixed sizes.
// Do not edit by hand — re-run the generator. Design system version 1.

import CoreGraphics

/// The measurements the design fixes: a 4-point spacing base, five radii, and
/// the three heights that are not negotiable.
///
/// `radiusFull` is deliberately absent. On the web it is `9999px`; in SwiftUI a
/// fully-rounded end is `Capsule()`, a different shape rather than a large
/// number, and the design allows it for read-only pills only.
public extension Midad {
    // MARK: - Spacing
    //
    // 4px base. Screens use a 16px side gutter; related rows sit 8px apart,
    // sections 24px.

    /// Between a label and its value; inside pills.
    static let space1: CGFloat = 4

    /// Between chips and between options.
    static let space2: CGFloat = 8

    /// Inside chips and rows; between an ask and its options.
    static let space3: CGFloat = 12

    /// Screen side gutter; card padding.
    static let space4: CGFloat = 16

    /// Sheet and prompt-card padding.
    static let space5: CGFloat = 20

    /// Between sections of a screen.
    static let space6: CGFloat = 24

    /// Above a screen title; around the hero word.
    static let space8: CGFloat = 32

    /// Clearance above the tab bar.
    static let space10: CGFloat = 40

    // MARK: - Radii
    //
    // Soft, not round. Pills only for read-only tags.

    /// Root tiles, tick boxes, highlighted clusters.
    static let radiusXs: CGFloat = 6

    /// Chips, segmented controls, inputs.
    static let radiusSm: CGFloat = 10

    /// Answer options, buttons, list groups, the paradigm grid.
    static let radiusMd: CGFloat = 14

    /// Prompt cards, the answer sheet's top corners, the stats card.
    static let radiusLg: CGFloat = 24

    // MARK: - Fixed sizes
    //
    // Hit areas and fixed chrome.

    /// Minimum height and width of anything tappable.
    static let tapTarget: CGFloat = 44

    /// Minimum height of an answer option, so a 28px Arabic word keeps its ḥarakāt clear.
    static let optionHeight: CGFloat = 60

    /// The sticky setup bar on Practice; content scrolls under it.
    static let setupBarHeight: CGFloat = 76
}
