// GENERATED by ios/tools/generate-tokens.mjs from design/midad/tokens.json.
// The twenty semantic colours, as one namespace over Assets.xcassets/Colors.
// Do not edit by hand — re-run the generator. Design system version 1.

import SwiftUI

/// The Midād palette — ink on paper, and one rubric red.
///
/// **Two channels that never cross** (product-spec D-58, rule 3): `sign` marks
/// the letters that carry the grammar and never fills a box; `correct` and
/// `wrong` colour an option's fill, border, mark and word and never a letter.
/// Success leans teal so it never pairs with `wrong` on the red–green axis,
/// and every verdict carries an icon and a word besides its colour.
///
/// Namespaced rather than hung off `Color` because several token names —
/// `fill`, `line`, `background` — already exist on SwiftUI's `ShapeStyle`,
/// where a bare `.fill` would resolve to the wrong one. The prefix also makes
/// the D1 exit criterion greppable: a colour anywhere downstream that is not
/// `Midad.something` is a hard-coded colour.
///
/// Night is an *appearance* inside each colour set, not a second palette, so
/// nothing that reads a token has to know which theme is showing.
public enum Midad {
    /// Page background of every screen.
    ///
    /// Paper `#f6f2ea` · Night `#171512`
    public static let ground = Color(.ground)

    /// Cards, answer options at rest, the answer sheet, the setup bar, the tab bar.
    ///
    /// Paper `#fffdf8` · Night `#211e1a`
    public static let raised = Color(.raised)

    /// Control backgrounds: inputs, progress tracks, segmented tracks, chart-map cells that are out of scope, pills. Darker than ground in light themes, lighter in dark ones.
    ///
    /// Paper `#ece6da` · Night `#2a2621`
    public static let fill = Color(.fill)

    /// Hairlines between rows and around raised surfaces. Decorative: never the only thing that marks out a control.
    ///
    /// Paper `#e0d8ca` · Night `#332e28`
    public static let line = Color(.line)

    /// Borders that identify a control (chips, options, inputs, root tiles). At least 3:1 on ground and raised in every theme.
    ///
    /// Paper `#8f8474` · Night `#7c7266`
    public static let lineStrong = Color(.lineStrong)

    /// Primary text and every Arabic word under study, on ground, raised, fill and every -soft tint (7:1 or better in every theme).
    ///
    /// Paper `#1d1a16` · Night `#eee7db`
    public static let ink = Color(.ink)

    /// Secondary text on ground, raised and fill: glosses, captions, pronoun hints, the English half of a bilingual label (4.5:1 or better).
    ///
    /// Paper `#5f574c` · Night `#ada395`
    public static let inkMuted = Color(.inkMuted)

    /// Disabled labels and decorative marks only. Never text a learner has to read.
    ///
    /// Paper `#9a9084` · Night `#6f675c`
    public static let inkFaint = Color(.inkFaint)

    /// The accent, and it has one job: the letters that carry the grammar, revealed after the answer (the diverging ḥaraka, the governing particle, later the affixes). A letter colour: on ground, raised and sign-soft, never a fill, border or icon.
    ///
    /// Paper `#b02e1c` · Night `#f47a5f`
    public static let sign = Color(.sign)

    /// Highlighter tint behind a revealed sign when it needs its own ground (the diverging cluster in a typed-answer diff). Not a container colour.
    ///
    /// Paper `#f7e3da` · Night `#3a221c`
    public static let signSoft = Color(.signSoft)

    /// The chosen state: selected chips and segments, the tick box of a picked checklist option, the outline of the met cell in a paradigm grid.
    ///
    /// Paper `#1d1a16` · Night `#eee7db`
    public static let select = Color(.select)

    /// Background of a checklist option that is picked but not yet checked, and of the met cell in a paradigm grid.
    ///
    /// Paper `#e9e2d5` · Night `#2f2a24`
    public static let selectSoft = Color(.selectSoft)

    /// Text and ticks on a select fill.
    ///
    /// Paper `#fffdf8` · Night `#171512`
    public static let onSelect = Color(.onSelect)

    /// The one primary button on a screen: Start, Check, Continue.
    ///
    /// Paper `#1d1a16` · Night `#eee7db`
    public static let action = Color(.action)

    /// Label on an action fill.
    ///
    /// Paper `#fffdf8` · Night `#171512`
    public static let onAction = Color(.onAction)

    /// Verdict text, the tick, and the border of a right option after grading; on ground, raised and correct-soft.
    ///
    /// Paper `#16705d` · Night `#62cfb1`
    public static let correct = Color(.correct)

    /// Fill of the option you got right.
    ///
    /// Paper `#dcefe7` · Night `#15302a`
    public static let correctSoft = Color(.correctSoft)

    /// Verdict text, the cross, and the border of a wrong pick; on ground, raised and wrong-soft. In Midād it is a neutral ink, because red belongs to the sign.
    ///
    /// Paper `#4f473e` · Night `#c2b8a9`
    public static let wrong = Color(.wrong)

    /// Fill of a wrong pick after grading.
    ///
    /// Paper `#e9e2d5` · Night `#2f2a24`
    public static let wrongSoft = Color(.wrongSoft)

    /// Keyboard focus ring: 2px of this, outside a 2px gap in ground (see focus-ring). At least 3:1 on ground, raised and fill.
    ///
    /// Paper `#1d1a16` · Night `#eee7db`
    public static let focus = Color(.focus)
}
