// GENERATED by ios/tools/generate-tokens.mjs from design/midad/tokens.json.
// The type scale. TypeStyle itself — how a style becomes a font — is hand-written next door.
// Do not edit by hand — re-run the generator. Design system version 1.

import SwiftUI

/// The Midād type scale: **three voices, three faces** (product-spec D-59).
///
/// Arabic (`arabic*`) is the object of study, the serif italic is a *meaning*,
/// the sans is the interface talking. Nothing else gets a face.
///
/// Every style carries an explicit `lineHeight`, which is the whole point:
/// vowelled Arabic is taller than a font's nominal line box and a shadda over a
/// ḍamma stacks two marks, so Scheherazade’s own metrics are not enough. D-59
/// obliges explicit row heights rather than fighting them — see `TypeStyle`.
public extension TypeStyle {
    // MARK: - Arabic — the object of study
    //
    // Scheherazade New, hosted by Google Fonts on the web and bundled in the iOS
    // app (SIL Open Font License). Arabic sits about 1.35× the size of the Latin
    // beside it and never goes below 19px; vocalised lines need 1.7× leading so
    // stacked ḥarakāt clear the line above.

    /// The word under study on a prompt card. One per screen.
    ///
    /// `60 / 104` — e.g. تَنْصُرُ
    static let arabicHero = TypeStyle(
        face: .arabic,
        size: 60,
        lineHeight: 104,
        weight: 400,
        italic: false,
        tracking: 0,
        ramp: .largeTitle
    )

    /// The verb on a derived-noun card, the citation in a table header, root-tile letters.
    ///
    /// `40 / 70` — e.g. اِسْتَخْرَجَ يَسْتَخْرِجُ
    static let arabicDisplay = TypeStyle(
        face: .arabic,
        size: 40,
        lineHeight: 70,
        weight: 400,
        italic: false,
        tracking: 0,
        ramp: .title
    )

    /// Answer options, the typed answer, the diff lines.
    ///
    /// `28 / 50` — e.g. لَمْ تَسْلَمَا
    static let arabicTitle = TypeStyle(
        face: .arabic,
        size: 28,
        lineHeight: 50,
        weight: 400,
        italic: false,
        tracking: 0,
        ramp: .title2
    )

    /// Paradigm-grid cells.
    ///
    /// `24 / 42` — e.g. نَصَرْتُمَا
    static let arabicCell = TypeStyle(
        face: .arabic,
        size: 24,
        lineHeight: 42,
        weight: 400,
        italic: false,
        tracking: 0,
        ramp: .title3
    )

    /// Arabic inside running text: the answer sheet, tips, the quote.
    ///
    /// `21 / 36` — e.g. فِعْل مُضَارِع مَعْلُوم
    static let arabicBody = TypeStyle(
        face: .arabic,
        size: 21,
        lineHeight: 36,
        weight: 400,
        italic: false,
        tracking: 0,
        ramp: .body
    )

    /// The Arabic half of a chip, pill or pronoun label.
    ///
    /// `19 / 30` — e.g. مَعْلُوم
    static let arabicLabel = TypeStyle(
        face: .arabic,
        size: 19,
        lineHeight: 30,
        weight: 400,
        italic: false,
        tracking: 0,
        ramp: .subheadline
    )

    // MARK: - Serif — the voice of meaning
    //
    // Newsreader. Anything that is a meaning (a gloss, an English reading, a
    // translation) is set in this italic, so it never reads as interface.

    /// The title at the top of a tab.
    ///
    /// `30 / 36`, weight 500 — e.g. Practice
    static let screenTitle = TypeStyle(
        face: .serif,
        size: 30,
        lineHeight: 36,
        weight: 500,
        italic: false,
        tracking: -0.01,
        ramp: .largeTitle
    )

    /// The English reading on a meaning card, at the size the Arabic word gets elsewhere.
    ///
    /// `28 / 36`, italic — e.g. “they two (f) were not safe”
    static let meaningDisplay = TypeStyle(
        face: .serif,
        size: 28,
        lineHeight: 36,
        weight: 400,
        italic: true,
        tracking: 0,
        ramp: .title2
    )

    /// The reading at the top of the answer sheet; the quote translation.
    ///
    /// `19 / 26`, italic — e.g. “she drank”
    static let reading = TypeStyle(
        face: .serif,
        size: 19,
        lineHeight: 26,
        weight: 400,
        italic: true,
        tracking: 0,
        ramp: .subheadline
    )

    /// The dictionary gloss under a word or a root.
    ///
    /// `17 / 24`, italic — e.g. “to help”
    static let gloss = TypeStyle(
        face: .serif,
        size: 17,
        lineHeight: 24,
        weight: 400,
        italic: true,
        tracking: 0,
        ramp: .callout
    )

    // MARK: - Sans — the voice of the interface
    //
    // The platform face: SF Pro on Apple devices, so Dynamic Type comes free in
    // SwiftUI. Sentence case everywhere; no tracked capitals.

    /// The question being asked, button labels, list-row titles.
    ///
    /// `17 / 24`, weight 600 — e.g. Who can the doer be?
    static let headline = TypeStyle(
        face: .sans,
        size: 17,
        lineHeight: 24,
        weight: 600,
        italic: false,
        tracking: 0,
        ramp: .headline
    )

    /// The first line of the answer sheet.
    ///
    /// `20 / 26`, weight 700 — e.g. Not quite
    static let verdict = TypeStyle(
        face: .sans,
        size: 20,
        lineHeight: 26,
        weight: 700,
        italic: false,
        tracking: 0,
        ramp: .title3
    )

    /// Explanations, tips, descriptions.
    ///
    /// `15 / 22` — e.g. Every muḍāriʿ opens with one of أ ن ي ت.
    static let body = TypeStyle(
        face: .sans,
        size: 15,
        lineHeight: 22,
        weight: 400,
        italic: false,
        tracking: 0,
        ramp: .body
    )

    /// Section labels, chip English, the English half of an option.
    ///
    /// `13 / 18`, weight 600 — e.g. Charts
    static let label = TypeStyle(
        face: .sans,
        size: 13,
        lineHeight: 18,
        weight: 600,
        italic: false,
        tracking: 0,
        ramp: .footnote
    )

    /// Counts, metadata, question kinds in the setup bar.
    ///
    /// `12 / 16`, weight 500 — e.g. ≈ 2,268 questions
    static let caption = TypeStyle(
        face: .sans,
        size: 12,
        lineHeight: 16,
        weight: 500,
        italic: false,
        tracking: 0,
        ramp: .caption
    )

    /// Stat numbers and the results score, with tabular figures.
    ///
    /// `32 / 38`, weight 600 — e.g. 7 / 10
    static let numeral = TypeStyle(
        face: .sans,
        size: 32,
        lineHeight: 38,
        weight: 600,
        italic: false,
        tracking: 0,
        ramp: .title,
        tabularFigures: true
    )
}
