// Nāqiṣ — the LĀM is weak (دَعَا, رَمَى). Engine-conjugated by NaqisConjugator.
// The type where the weak letter is likeliest to vanish outright, since it sits
// where the ending attaches and the two collide in most slots.
//
// TWO TYPES LIVE HERE, naqis_waw and naqis_ya, split by which letter is weak
// because that is what decides the iʿlāl. The student sees one chip, نَاقِص.
//
// Record shape, engine routing and the trans/bab/masdar conventions are
// documented once in the barrel, ../roots.js — read that first.

export const NAQIS_ROOTS = [
  // --- Nāqiṣ wāw · و as final radical ----------------------------------------
  {
    root: ['د', 'ع', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to call / invite', masdar: 'دَعْوَة', trans: true,
           en: { past: 'called', pp: 'called', pres3: 'calls', ing: 'calling' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AF%D9%8E%D8%B9%D9%8E%D8%A7.html' },
      VI: { gloss: 'to call on one another', trans: false,
            en: { past: 'called on one another', pres3: 'call on one another', ing: 'calling on one another' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AF%D9%8E%D8%A7%D8%B9%D9%8E%D9%89.html' },
      VIII: { gloss: 'to claim / allege', trans: true,
              en: { past: 'claimed', pp: 'claimed', pres3: 'claims', ing: 'claiming' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%AF%D9%91%D9%8E%D8%B9%D9%8E%D9%89.html' },
    },
  },
  {
    root: ['ن', 'ع', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to announce a death', masdar: 'نَعْي', trans: true,
           en: { past: 'announced the death of', pp: 'mourned', pres3: 'announces the death of', ing: 'announcing the death of' } },
    },
  },
  {
    root: ['ب', 'ه', 'و'], type: 'naqis_waw',
    forms: {
      // The third waw-lām root, and the first to reach the mazīd tables — where
      // its wāw surfaces as a yāʾ (بَاهَى · تَبَاهَى), the rule NAQIS_STEMS'
      // mazīd header states. دعو only ever gets there through VI and VIII.
      I: { bab: 'au', gloss: 'to be splendid', masdar: 'بَهَاء', trans: false,
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A8%D9%8E%D9%87%D9%8E%D8%A7.html' },
      III: { gloss: 'to vie in glory with', trans: true,
             en: { past: 'vied with', pp: 'vied with', pres3: 'vies with', ing: 'vying with' } },
      VI: { gloss: 'to boast to one another', trans: false,
            en: { past: 'boasted to one another', pres3: 'boast to one another', ing: 'boasting to one another' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%A8%D9%8E%D8%A7%D9%87%D9%8E%D9%89.html' },
    },
  },
  {
    root: ['س', 'م', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to be high / to rise', masdar: 'سُمُوّ', trans: false,
           en: { past: 'rose', pres3: 'rises', ing: 'rising' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D9%85%D9%8E%D8%A7.html' },
      II: { gloss: 'to name / to call', masdar: 'تَسْمِيَة', trans: true,
            en: { past: 'named', pp: 'named', pres3: 'names', ing: 'naming' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D9%85%D9%91%D9%8E%D9%89.html' },
      III: { gloss: 'to vie with in glory', masdar: 'مُسَامَاة', trans: true,
             en: { past: 'vied with', pp: 'vied with', pres3: 'vies with', ing: 'vying with' } },
      IV: { gloss: 'to elevate / to raise up', masdar: 'إِسْمَاء', trans: true,
            en: { past: 'elevated', pp: 'elevated', pres3: 'elevates', ing: 'elevating' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%B3%D9%92%D9%85%D9%8E%D9%89.html' },
      V: { gloss: 'to be named / to go by the name of', masdar: 'تَسَمٍّ', trans: false,
           en: { past: 'was named', pres3: 'is named', ing: 'being named' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B3%D9%8E%D9%85%D9%91%D9%8E%D9%89.html' },
      VI: { gloss: 'to rise high / to vie with one another', masdar: 'تَسَامٍ', trans: false,
            en: { past: 'rose high', pres3: 'rises high', ing: 'rising high' } },
    },
  },
  {
    root: ['ر', 'ب', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to grow / to increase', masdar: 'رُبُوّ', trans: false,
           en: { past: 'grew', pres3: 'grows', ing: 'growing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B1%D9%8E%D8%A8%D9%8E%D8%A7.html' },
      II: { gloss: 'to raise / to bring up / to educate', masdar: 'تَرْبِيَة', trans: true,
            en: { past: 'raised', pp: 'raised', pres3: 'raises', ing: 'raising' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B1%D9%8E%D8%A8%D9%91%D9%8E%D9%89.html' },
      III: { gloss: 'to practise usury with', masdar: 'مُرَابَاة', trans: true,
             en: { past: 'lent at interest to', pp: 'lent at interest to', pres3: 'lends at interest to', ing: 'lending at interest to' } },
      IV: { gloss: 'to exceed / to surpass', masdar: 'إِرْبَاء', trans: false,
            en: { past: 'exceeded', pres3: 'exceeds', ing: 'exceeding' } },
      V: { gloss: 'to be brought up / to be reared', masdar: 'تَرَبٍّ', trans: false,
           en: { past: 'was raised', pres3: 'is raised', ing: 'being raised' } },
    },
  },
  {
    root: ['غ', 'ذ', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to feed / to nourish', masdar: 'غَذْو', trans: true,
           en: { past: 'fed', pp: 'fed', pres3: 'feeds', ing: 'feeding' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%BA%D9%8E%D8%B0%D9%8E%D8%A7.html' },
      II: { gloss: 'to nourish / to nurture / to feed', masdar: 'تَغْذِيَة', trans: true,
            en: { past: 'nourished', pp: 'nourished', pres3: 'nourishes', ing: 'nourishing' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%BA%D9%8E%D8%B0%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to be nourished / to feed on / to eat', masdar: 'تَغَذٍّ', trans: false,
           en: { past: 'fed on', pres3: 'feeds on', ing: 'feeding on' } },
      VIII: { gloss: 'to be nourished / to subsist on', masdar: 'اِغْتِذَاء', trans: false,
              en: { past: 'subsisted on', pres3: 'subsists on', ing: 'subsisting on' } },
    },
  },
  {
    root: ['ح', 'ل', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to be sweet / to be pleasant', masdar: 'حَلَاوَة', trans: false,
           en: { past: 'was sweet', pres3: 'is sweet', ing: 'being sweet' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AD%D9%8E%D9%84%D9%8E%D8%A7.html' },
      II: { gloss: 'to sweeten / to adorn / to decorate', masdar: 'تَحْلِيَة', trans: true,
            en: { past: 'sweetened', pp: 'sweetened', pres3: 'sweetens', ing: 'sweetening' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AD%D9%8E%D9%84%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to sweeten / to make pleasant', masdar: 'إِحْلَاء', trans: true,
            en: { past: 'sweetened', pp: 'sweetened', pres3: 'sweetens', ing: 'sweetening' } },
      V: { gloss: 'to be adorned with / to be endowed with', masdar: 'تَحَلٍّ', trans: false,
           en: { past: 'was adorned with', pres3: 'is adorned with', ing: 'being adorned with' } },
      X: { gloss: 'to find sweet / to relish', masdar: 'اِسْتِحْلَاء', trans: true,
           en: { past: 'relished', pp: 'relished', pres3: 'relishes', ing: 'relishing' } },
    },
  },
  {
    root: ['غ', 'ط', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to cover / to overspread', masdar: 'غَطْو', trans: true,
           en: { past: 'covered', pp: 'covered', pres3: 'covers', ing: 'covering' } },
      II: { gloss: 'to cover / to conceal / to cover (costs, a story)', masdar: 'تَغْطِيَة', trans: true,
            en: { past: 'covered', pp: 'covered', pres3: 'covers', ing: 'covering' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%BA%D9%8E%D8%B7%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to be covered / to cover oneself', masdar: 'تَغَطٍّ', trans: false,
           en: { past: 'covered up', pres3: 'covers up', ing: 'covering up' } },
    },
  },
  {
    root: ['خ', 'ل', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to be empty / to be free of', masdar: 'خُلُوّ', trans: false,
           en: { past: 'was empty', pres3: 'is empty', ing: 'being empty' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AE%D9%8E%D9%84%D9%8E%D8%A7.html' },
      II: { gloss: 'to leave / to let be / to vacate', masdar: 'تَخْلِيَة', trans: true,
            en: { past: 'left alone', pp: 'left alone', pres3: 'leaves alone', ing: 'leaving alone' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AE%D9%8E%D9%84%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to empty / to evacuate / to release', masdar: 'إِخْلَاء', trans: true,
            en: { past: 'evacuated', pp: 'evacuated', pres3: 'evacuates', ing: 'evacuating' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%AE%D9%92%D9%84%D9%8E%D9%89.html' },
      V: { gloss: 'to give up / to renounce / to abandon', masdar: 'تَخَلٍّ', trans: true,
           en: { past: 'gave up', pres3: 'gives up', ing: 'giving up' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AE%D9%8E%D9%84%D9%91%D9%8E%D9%89.html' },
      X: { gloss: 'to seek privacy / to be alone with', masdar: 'اِسْتِخْلَاء', trans: false,
           en: { past: 'withdrew in private', pres3: 'withdraws in private', ing: 'withdrawing in private' } },
    },
  },
  {
    root: ['س', 'ل', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to forget / to be consoled', masdar: 'سُلُوّ', trans: false,
           en: { past: 'got over', pres3: 'gets over', ing: 'getting over' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D9%84%D9%8E%D8%A7.html' },
      II: { gloss: 'to comfort / to divert / to entertain', masdar: 'تَسْلِيَة', trans: true,
            en: { past: 'entertained', pp: 'entertained', pres3: 'entertains', ing: 'entertaining' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D9%84%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to console / to make forget', masdar: 'إِسْلَاء', trans: true,
            en: { past: 'consoled', pp: 'consoled', pres3: 'consoles', ing: 'consoling' } },
      V: { gloss: 'to amuse oneself / to be entertained', masdar: 'تَسَلٍّ', trans: true,
           en: { past: 'was amused', pres3: 'is amused', ing: 'being amused' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B3%D9%8E%D9%84%D9%91%D9%8E%D9%89.html' },
    },
  },
  {
    root: ['ع', 'د', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to run / to pass by / to exceed', masdar: 'عَدْو', trans: false,
           en: { past: 'ran', pres3: 'runs', ing: 'running' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B9%D9%8E%D8%AF%D9%8E%D8%A7.html' },
      II: { gloss: 'to make pass / to take across / to transfer', masdar: 'تَعْدِيَة', trans: true,
            en: { past: 'took across', pp: 'taken across', pres3: 'takes across', ing: 'taking across' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B9%D9%8E%D8%AF%D9%91%D9%8E%D9%89.html' },
      III: { gloss: 'to be hostile to / to treat as an enemy', masdar: 'مُعَادَاة', trans: true,
             en: { past: 'opposed', pp: 'opposed', pres3: 'opposes', ing: 'opposing' } },
      IV: { gloss: 'to infect / to contaminate', masdar: 'إِعْدَاء', trans: true,
            en: { past: 'infected', pp: 'infected', pres3: 'infects', ing: 'infecting' } },
      V: { gloss: 'to exceed / to transgress / to encroach on', masdar: 'تَعَدٍّ', trans: true,
           en: { past: 'exceeded', pp: 'exceeded', pres3: 'exceeds', ing: 'exceeding' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B9%D9%8E%D8%AF%D9%91%D9%8E%D9%89.html' },
      VI: { gloss: 'to be mutually hostile', masdar: 'تَعَادٍ', trans: false,
            en: { past: 'were at odds', pres3: 'are at odds', ing: 'being at odds' } },
      VIII: { gloss: 'to attack / to assault / to infringe on', masdar: 'اِعْتِدَاء', trans: false,
              en: { past: 'attacked', pres3: 'attacks', ing: 'attacking' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B9%D9%92%D8%AA%D9%8E%D8%AF%D9%8E%D9%89.html' },
      X: { gloss: 'to seek redress against / to incite against', masdar: 'اِسْتِعْدَاء', trans: true,
           en: { past: 'incited against', pp: 'incited against', pres3: 'incites against', ing: 'inciting against' } },
    },
  },
  {
    root: ['ق', 'ف', 'و'], type: 'naqis_waw',
    forms: {
      I: { bab: 'au', gloss: 'to follow / to trail', masdar: 'قَفْو', trans: true,
           en: { past: 'trailed', pp: 'trailed', pres3: 'trails', ing: 'trailing' } },
      II: { gloss: 'to make follow / to send after / to rhyme', masdar: 'تَقْفِيَة', trans: true,
            en: { past: 'sent after', pp: 'sent after', pres3: 'sends after', ing: 'sending after' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%82%D9%8E%D9%81%D9%91%D9%8E%D9%89.html' },
      VIII: { gloss: 'to follow / to track / to trace', masdar: 'اِقْتِفَاء', trans: true,
              en: { past: 'tracked', pp: 'tracked', pres3: 'tracks', ing: 'tracking' } },
    },
  },
  {
    root: ['ص', 'ل', 'و'], type: 'naqis_waw',
    note: 'Reverso only resolves this correctly when typed fully vocalized as صَلَّى. Form I of ص-ل-و is archaic; the homographic root ص-ل-ي means "to roast, burn".',
    forms: {
      II: { gloss: 'to pray / to perform the ṣalāh / to invoke blessing upon', masdar: 'صَلَاة', trans: false,
            en: { past: 'prayed', pres3: 'prays', ing: 'praying' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B5%D9%8E%D9%84%D9%91%D9%8E%D9%89.html' },
    },
  },
  {
    root: ['ن', 'م', 'و'], type: 'naqis_waw',
    note: 'Type this one fully vocalized as نَمَّى — bare نمّى returns the Form I paradigm.',
    forms: {
      I: { bab: 'au', gloss: 'to grow / to increase', masdar: 'نُمُوّ', trans: false,
           en: { past: 'grew', pres3: 'grows', ing: 'growing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D9%85%D9%8E%D8%A7.html' },
      II: { gloss: 'to develop / to cultivate / to make grow', masdar: 'تَنْمِيَة', trans: true,
            en: { past: 'developed', pp: 'developed', pres3: 'develops', ing: 'developing' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D9%85%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to make grow / to increase', masdar: 'إِنْمَاء', trans: true,
            en: { past: 'increased', pp: 'increased', pres3: 'increases', ing: 'increasing' } },
      V: { gloss: 'to grow / to develop', masdar: 'تَنَمٍّ', trans: false,
           en: { past: 'developed', pres3: 'develops', ing: 'developing' } },
      VIII: { gloss: 'to belong to / to be affiliated with', masdar: 'اِنْتِمَاء', trans: false,
              en: { past: 'belonged to', pres3: 'belongs to', ing: 'belonging to' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D9%86%D9%92%D8%AA%D9%8E%D9%85%D9%8E%D9%89.html' },
    },
  },
  // --- Nāqiṣ yāʾ · ي as final radical ----------------------------------------
  {
    root: ['ر', 'م', 'ي'], type: 'naqis_ya',
    forms: {
      I: {
        bab: 'ai', gloss: 'to throw', masdar: 'رَمْي', trans: true,
        en: { past: 'threw', pp: 'thrown', pres3: 'throws', ing: 'throwing' },
        manualTables: {
          madi_malum: {
            '3ms': 'رَمَى', '3md': 'رَمَيَا', '3mp': 'رَمَوْا',
            '3fs': 'رَمَتْ', '3fd': 'رَمَتَا', '3fp': 'رَمَيْنَ',
            '2ms': 'رَمَيْتَ', '2md': 'رَمَيْتُمَا', '2mp': 'رَمَيْتُمْ',
            '2fs': 'رَمَيْتِ', '2fd': 'رَمَيْتُمَا', '2fp': 'رَمَيْتُنَّ',
            '1s': 'رَمَيْتُ', '1p': 'رَمَيْنَا',
          },
          madi_majhul: {
            '3ms': 'رُمِيَ', '3md': 'رُمِيَا', '3mp': 'رُمُوا',
            '3fs': 'رُمِيَتْ', '3fd': 'رُمِيَتَا', '3fp': 'رُمِينَ',
            '2ms': 'رُمِيتَ', '2md': 'رُمِيتُمَا', '2mp': 'رُمِيتُمْ',
            '2fs': 'رُمِيتِ', '2fd': 'رُمِيتُمَا', '2fp': 'رُمِيتُنَّ',
            '1s': 'رُمِيتُ', '1p': 'رُمِينَا',
          },
          mudari_malum_raf: {
            '3ms': 'يَرْمِي', '3md': 'يَرْمِيَانِ', '3mp': 'يَرْمُونَ',
            '3fs': 'تَرْمِي', '3fd': 'تَرْمِيَانِ', '3fp': 'يَرْمِينَ',
            '2ms': 'تَرْمِي', '2md': 'تَرْمِيَانِ', '2mp': 'تَرْمُونَ',
            '2fs': 'تَرْمِينَ', '2fd': 'تَرْمِيَانِ', '2fp': 'تَرْمِينَ',
            '1s': 'أَرْمِي', '1p': 'نَرْمِي',
          },
          mudari_majhul_raf: {
            '3ms': 'يُرْمَى', '3md': 'يُرْمَيَانِ', '3mp': 'يُرْمَوْنَ',
            '3fs': 'تُرْمَى', '3fd': 'تُرْمَيَانِ', '3fp': 'يُرْمَيْنَ',
            '2ms': 'تُرْمَى', '2md': 'تُرْمَيَانِ', '2mp': 'تُرْمَوْنَ',
            '2fs': 'تُرْمَيْنَ', '2fd': 'تُرْمَيَانِ', '2fp': 'تُرْمَيْنَ',
            '1s': 'أُرْمَى', '1p': 'نُرْمَى',
          },
          mudari_malum_nasb: {
            '3ms': 'يَرْمِيَ', '3md': 'يَرْمِيَا', '3mp': 'يَرْمُوا',
            '3fs': 'تَرْمِيَ', '3fd': 'تَرْمِيَا', '3fp': 'يَرْمِينَ',
            '2ms': 'تَرْمِيَ', '2md': 'تَرْمِيَا', '2mp': 'تَرْمُوا',
            '2fs': 'تَرْمِي', '2fd': 'تَرْمِيَا', '2fp': 'تَرْمِينَ',
            '1s': 'أَرْمِيَ', '1p': 'نَرْمِيَ',
          },
          mudari_malum_jazm: {
            '3ms': 'يَرْمِ', '3md': 'يَرْمِيَا', '3mp': 'يَرْمُوا',
            '3fs': 'تَرْمِ', '3fd': 'تَرْمِيَا', '3fp': 'يَرْمِينَ',
            '2ms': 'تَرْمِ', '2md': 'تَرْمِيَا', '2mp': 'تَرْمُوا',
            '2fs': 'تَرْمِي', '2fd': 'تَرْمِيَا', '2fp': 'تَرْمِينَ',
            '1s': 'أَرْمِ', '1p': 'نَرْمِ',
          },
          amr_malum: {
            '2ms': 'اِرْمِ', '2md': 'اِرْمِيَا', '2mp': 'اِرْمُوا',
            '2fs': 'اِرْمِي', '2fd': 'اِرْمِيَا', '2fp': 'اِرْمِينَ',
          },
        },
        reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B1%D9%8E%D9%85%D9%8E%D9%89.html',
      },
      // Form I is fixture-checked; VI and VIII are the naqis mazīd tables
      // (ROADMAP B1) doing the work, same as قضي and رضي.
      VI: { gloss: 'to shoot at one another', trans: false,
            en: { past: 'shot at one another', pres3: 'shoot at one another', ing: 'shooting at one another' } },
      VIII: { gloss: 'to fling oneself', trans: false,
              en: { past: 'flung himself', pres3: 'flings himself', ing: 'flinging himself' } },
    },
  },
  {
    root: ['ق', 'ض', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ai', gloss: 'to decide / judge', masdar: 'قَضَاء', trans: true,
           en: { past: 'judged', pp: 'judged', pres3: 'judges', ing: 'judging' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%82%D9%8E%D8%B6%D9%8E%D9%89.html' },
      III: { gloss: 'to take to court', trans: true,
             en: { past: 'sued', pp: 'sued', pres3: 'sues', ing: 'suing' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%82%D9%8E%D8%A7%D8%B6%D9%8E%D9%89.html' },
      VI: { gloss: 'to sue each other', trans: false,
            en: { past: 'sued each other', pres3: 'sue each other', ing: 'suing each other' } },
      VII: { gloss: 'to elapse / come to an end', trans: false,
             en: { past: 'elapsed', pres3: 'elapses', ing: 'elapsing' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D9%86%D9%92%D9%82%D9%8E%D8%B6%D9%8E%D9%89.html' },
      VIII: { gloss: 'to require / necessitate', trans: true,
              en: { past: 'required', pp: 'required', pres3: 'requires', ing: 'requiring' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D9%82%D9%92%D8%AA%D9%8E%D8%B6%D9%8E%D9%89.html' },
    },
  },
  {
    root: ['س', 'ع', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'aa', gloss: 'to strive / endeavour', masdar: 'سَعْي', trans: false,
           en: { past: 'strove', pres3: 'strives', ing: 'striving' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D8%B9%D9%8E%D9%89.html' },
      X: { gloss: 'to ask someone to make an effort', trans: true,
           en: { past: 'asked to make an effort', pp: 'called upon', pres3: 'asks to make an effort', ing: 'asking to make an effort' } },
    },
  },
  {
    root: ['ر', 'ض', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ia', gloss: 'to be pleased / content', masdar: 'رِضًا', trans: false,
           en: { past: 'was pleased', pres3: 'is pleased', ing: 'being pleased' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B1%D9%8E%D8%B6%D9%90%D9%8A%D9%8E.html' },
      III: { gloss: 'to appease', trans: true,
             en: { past: 'appeased', pp: 'appeased', pres3: 'appeases', ing: 'appeasing' } },
      IV: { gloss: 'to satisfy / please', trans: true,
            en: { past: 'satisfied', pp: 'satisfied', pres3: 'satisfies', ing: 'satisfying' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%B1%D9%92%D8%B6%D9%8E%D9%89.html' },
      VI: { gloss: 'to reach mutual agreement', trans: false,
            en: { past: 'reached mutual agreement', pres3: 'reach mutual agreement', ing: 'reaching mutual agreement' } },
      VIII: { gloss: 'to approve of', trans: true,
              en: { past: 'approved of', pp: 'approved of', pres3: 'approves of', ing: 'approving of' } },
    },
  },
  {
    root: ['ه', 'د', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ai', gloss: 'to guide', masdar: 'هُدًى', trans: true,
           en: { past: 'guided', pp: 'guided', pres3: 'guides', ing: 'guiding' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%87%D9%8E%D8%AF%D9%8E%D9%89.html' },
      IV: { gloss: 'to give as a gift', trans: true,
            en: { past: 'gave as a gift', pp: 'given as a gift', pres3: 'gives as a gift', ing: 'giving as a gift' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D9%87%D9%92%D8%AF%D9%8E%D9%89.html' },
      VI: { gloss: 'to exchange gifts', trans: false,
            en: { past: 'exchanged gifts', pres3: 'exchange gifts', ing: 'exchanging gifts' } },
      VIII: { gloss: 'to be rightly guided', trans: false,
              en: { past: 'was rightly guided', pres3: 'is rightly guided', ing: 'being rightly guided' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D9%87%D9%92%D8%AA%D9%8E%D8%AF%D9%8E%D9%89.html' },
      X: { gloss: 'to seek guidance', trans: false,
           en: { past: 'sought guidance', pres3: 'seeks guidance', ing: 'seeking guidance' } },
    },
  },
  {
    root: ['ب', 'ق', 'ي'], type: 'naqis_ya',
    forms: {
      // bab سَمِعَ — the one nāqiṣ bab whose lām survives almost everywhere,
      // because the kasra on the ʿayn makes the yāʾ pronounceable. Same shape
      // as رَضِيَ, and the second root to exercise it.
      I: { bab: 'ia', gloss: 'to remain', masdar: 'بَقَاء', trans: false,
           en: { past: 'remained', pres3: 'remains', ing: 'remaining' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A8%D9%8E%D9%82%D9%90%D9%8A%D9%8E.html' },
      II: { gloss: 'to leave over', trans: true,
            en: { past: 'left over', pp: 'left over', pres3: 'leaves over', ing: 'leaving over' } },
      IV: { gloss: 'to spare', trans: true,
            en: { past: 'spared', pp: 'spared', pres3: 'spares', ing: 'sparing' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%A8%D9%92%D9%82%D9%8E%D9%89.html' },
      X: { gloss: 'to keep alive', trans: true,
           en: { past: 'kept alive', pp: 'kept alive', pres3: 'keeps alive', ing: 'keeping alive' } },
    },
  },
  {
    root: ['ل', 'ب', 'ي'], type: 'naqis_ya',
    note: 'Form I is archaic; in MSA this root is effectively Form II only.',
    forms: {
      II: { gloss: 'to comply with / to answer (a call) / to meet (a need)', masdar: 'تَلْبِيَة', trans: true,
            en: { past: 'complied with', pp: 'complied with', pres3: 'complies with', ing: 'complying with' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%84%D9%8E%D8%A8%D9%91%D9%8E%D9%89.html' },
    },
  },
  {
    root: ['ع', 'ز', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ia', gloss: 'to be patient / to bear with fortitude', masdar: 'عَزَاء', trans: false,
           en: { past: 'bore patiently', pres3: 'bears patiently', ing: 'bearing patiently' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B9%D9%8E%D8%B2%D9%90%D9%8A%D9%8E.html' },
      II: { gloss: 'to console / to offer condolences to', masdar: 'تَعْزِيَة', trans: true,
            en: { past: 'consoled', pp: 'consoled', pres3: 'consoles', ing: 'consoling' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B9%D9%8E%D8%B2%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to be consoled / to take comfort', masdar: 'تَعَزٍّ', trans: false,
           en: { past: 'took comfort', pres3: 'takes comfort', ing: 'taking comfort' } },
    },
  },
  {
    root: ['أ', 'د', 'ي'], type: 'naqis_ya',
    note: 'Also mahmūz al-fāʾ, so the hamza carries its own spelling rules.',
    forms: {
      II: { gloss: 'to carry out / to perform / to pay', masdar: 'تَأْدِيَة', trans: true,
            en: { past: 'carried out', pp: 'carried out', pres3: 'carries out', ing: 'carrying out' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%AF%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to lead to / to result in', masdar: 'تَأَدٍّ', trans: false,
           en: { past: 'led to', pres3: 'leads to', ing: 'leading to' } },
    },
  },
  {
    root: ['غ', 'ن', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ia', gloss: 'to be rich / to do without', masdar: 'غِنًى', trans: false,
           en: { past: 'was rich', pres3: 'is rich', ing: 'being rich' } },
      II: { gloss: 'to sing', masdar: 'تَغْنِيَة', trans: true,
            en: { past: 'sang', pp: 'sung', pres3: 'sings', ing: 'singing' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%BA%D9%8E%D9%86%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to enrich / to suffice / to avail', masdar: 'إِغْنَاء', trans: true,
            en: { past: 'enriched', pp: 'enriched', pres3: 'enriches', ing: 'enriching' } },
      V: { gloss: 'to sing / to extol', masdar: 'تَغَنٍّ', trans: false,
           en: { past: 'sang of', pres3: 'sings of', ing: 'singing of' } },
      VIII: { gloss: 'to become rich', masdar: 'اِغْتِنَاء', trans: false,
              en: { past: 'became rich', pres3: 'becomes rich', ing: 'becoming rich' } },
      X: { gloss: 'to do without / to dispense with', masdar: 'اِسْتِغْنَاء', trans: false,
           en: { past: 'did without', pres3: 'does without', ing: 'doing without' } },
    },
  },
  {
    root: ['م', 'ن', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ai', gloss: 'to destine / to afflict (with)', masdar: 'مَنْي', trans: true,
           en: { past: 'destined', pp: 'destined', pres3: 'destines', ing: 'destining' } },
      II: { gloss: 'to raise the hopes of / to make (someone) wish', masdar: 'تَمْنِيَة', trans: true,
            en: { past: 'raised hopes of', pp: 'given hope', pres3: 'raises hopes of', ing: 'raising hopes of' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%85%D9%8E%D9%86%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to wish / to desire', masdar: 'تَمَنٍّ', trans: true,
           en: { past: 'wished', pp: 'wished for', pres3: 'wishes', ing: 'wishing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D9%85%D9%8E%D9%86%D9%91%D9%8E%D9%89.html' },
    },
  },
  {
    root: ['ك', 'ن', 'ي'], type: 'naqis_ya',
    note: 'Reverso uses كَنَّى as the model verb for this whole Form II nāqiṣ class.',
    forms: {
      I: { bab: 'ai', gloss: 'to allude to / to speak indirectly of', masdar: 'كِنَايَة', trans: false,
           en: { past: 'alluded to', pres3: 'alludes to', ing: 'alluding to' } },
      II: { gloss: 'to give a kunya to / to nickname', masdar: 'تَكْنِيَة', trans: true,
            en: { past: 'nicknamed', pp: 'nicknamed', pres3: 'nicknames', ing: 'nicknaming' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%83%D9%8E%D9%86%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to be nicknamed / to take a kunya', masdar: 'تَكَنٍّ', trans: false,
           en: { past: 'was nicknamed', pres3: 'is nicknamed', ing: 'being nicknamed' } },
    },
  },
  {
    root: ['ن', 'ق', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ia', gloss: 'to be clean / to be pure', masdar: 'نَقَاء', trans: false,
           en: { past: 'was clean', pres3: 'is clean', ing: 'being clean' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D9%82%D9%90%D9%8A%D9%8E.html' },
      II: { gloss: 'to clean / to purify / to sift', masdar: 'تَنْقِيَة', trans: true,
            en: { past: 'purified', pp: 'purified', pres3: 'purifies', ing: 'purifying' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D9%82%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to be cleaned / to be purified', masdar: 'تَنَقٍّ', trans: false,
           en: { past: 'was purified', pres3: 'is purified', ing: 'being purified' } },
      VIII: { gloss: 'to select / to pick out', masdar: 'اِنْتِقَاء', trans: true,
              en: { past: 'selected', pp: 'selected', pres3: 'selects', ing: 'selecting' } },
    },
  },
  {
    root: ['ن', 'س', 'ي'], type: 'naqis_ya',
    forms: {
      I: { bab: 'ia', gloss: 'to forget', masdar: 'نِسْيَان', trans: true,
           en: { past: 'forgot', pp: 'forgotten', pres3: 'forgets', ing: 'forgetting' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D8%B3%D9%90%D9%8A%D9%8E.html' },
      II: { gloss: 'to make (someone) forget', masdar: 'تَنْسِيَة', trans: true,
            en: { past: 'made forget', pp: 'made to forget', pres3: 'makes forget', ing: 'making forget' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D8%B3%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to make forget / to cause to forget', masdar: 'إِنْسَاء', trans: true,
            en: { past: 'made forget', pp: 'made to forget', pres3: 'makes forget', ing: 'making forget' } },
      V: { gloss: 'to try to forget / to put out of mind', masdar: 'تَنَسٍّ', trans: true,
           en: { past: 'put out of mind', pp: 'put out of mind', pres3: 'puts out of mind', ing: 'putting out of mind' } },
      VI: { gloss: 'to feign forgetfulness / to deliberately ignore', masdar: 'تَنَاسٍ', trans: true,
            en: { past: 'deliberately ignored', pp: 'deliberately ignored', pres3: 'deliberately ignores', ing: 'deliberately ignoring' } },
    },
  },
  {
    root: ['ر', 'ق', 'ي'], type: 'naqis_ya',
    note: 'Type this one fully vocalized as رَقَّى — bare رقّى returns the Form I paradigm.',
    forms: {
      I: { bab: 'ia', gloss: 'to ascend / to climb / to rise', masdar: 'رُقِيّ', trans: false,
           en: { past: 'ascended', pres3: 'ascends', ing: 'ascending' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B1%D9%8E%D9%82%D9%90%D9%8A%D9%8E.html' },
      II: { gloss: 'to promote / to advance / to elevate', masdar: 'تَرْقِيَة', trans: true,
            en: { past: 'promoted', pp: 'promoted', pres3: 'promotes', ing: 'promoting' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B1%D9%8E%D9%82%D9%91%D9%8E%D9%89.html' },
      V: { gloss: 'to rise / to be promoted / to advance', masdar: 'تَرَقٍّ', trans: false,
           en: { past: 'was promoted', pres3: 'is promoted', ing: 'being promoted' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B1%D9%8E%D9%82%D9%91%D9%8E%D9%89.html' },
      VIII: { gloss: 'to ascend / to rise to', masdar: 'اِرْتِقَاء', trans: false,
              en: { past: 'rose to', pres3: 'rises to', ing: 'rising to' } },
    },
  },
  {
    root: ['غ', 'ل', 'ي'], type: 'naqis_ya',
    note: 'Type this one fully vocalized as غَلَّى — bare غلّى returns the Form I paradigm. Do not confuse with غ-ل-و "to be excessive / expensive".',
    forms: {
      I: { bab: 'ai', gloss: 'to boil / to come to a boil', masdar: 'غَلَيَان', trans: false,
           en: { past: 'boiled', pres3: 'boils', ing: 'boiling' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%BA%D9%8E%D9%84%D9%8E%D9%89.html' },
      II: { gloss: 'to bring to a boil / to make boil', masdar: 'تَغْلِيَة', trans: true,
            en: { past: 'boiled', pp: 'boiled', pres3: 'boils', ing: 'boiling' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%BA%D9%8E%D9%84%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to bring to a boil', masdar: 'إِغْلَاء', trans: true,
            en: { past: 'brought to a boil', pp: 'brought to a boil', pres3: 'brings to a boil', ing: 'bringing to a boil' } },
    },
  },
  {
    root: ['ث', 'ن', 'ي'], type: 'naqis_ya',
    note: 'Type this one fully vocalized as ثَنَّى — bare ثنّى returns the Form I paradigm.',
    forms: {
      I: { bab: 'ai', gloss: 'to fold / to bend / to turn away', masdar: 'ثَنْي', trans: true,
           en: { past: 'folded', pp: 'folded', pres3: 'folds', ing: 'folding' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AB%D9%8E%D9%86%D9%8E%D9%89.html' },
      II: { gloss: 'to double / to do twice / to make dual', masdar: 'تَثْنِيَة', trans: true,
            en: { past: 'doubled', pp: 'doubled', pres3: 'doubles', ing: 'doubling' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AB%D9%8E%D9%86%D9%91%D9%8E%D9%89.html' },
      IV: { gloss: 'to praise / to commend', masdar: 'ثَنَاء', trans: false,
            en: { past: 'praised', pres3: 'praises', ing: 'praising' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%AB%D9%92%D9%86%D9%8E%D9%89.html' },
      V: { gloss: 'to be doubled / to sway / to bend', masdar: 'تَثَنٍّ', trans: false,
           en: { past: 'swayed', pres3: 'sways', ing: 'swaying' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AB%D9%8E%D9%86%D9%91%D9%8E%D9%89.html' },
      VII: { gloss: 'to be bent / to bend / to turn away', masdar: 'اِنْثِنَاء', trans: false,
             en: { past: 'bent', pres3: 'bends', ing: 'bending' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D9%86%D9%92%D8%AB%D9%8E%D9%86%D9%8E%D9%89.html' },
      X: { gloss: 'to except / to exclude', masdar: 'اِسْتِثْنَاء', trans: true,
           en: { past: 'excluded', pp: 'excluded', pres3: 'excludes', ing: 'excluding' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D8%AB%D9%92%D9%86%D9%8E%D9%89.html' },
    },
  },
];
