// Sālim — no weak letter, no hamza, no doubled radical. The default type and
// the one every engine rule is stated against: SalimConjugator authors these
// straight from the templates, with no iʿlāl to apply.
//
// Record shape, engine routing and the trans/bab/masdar conventions are
// documented once in the barrel, ../roots.js — read that first.

export const SALIM_ROOTS = [
  {
    root: ['ك', 'ت', 'ب'], type: 'salim',
    forms: {
      I: { bab: 'au', gloss: 'to write', masdar: 'كِتَابَة', trans: true,
           en: { past: 'wrote', pp: 'written', pres3: 'writes', ing: 'writing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%83%D9%8E%D8%AA%D9%8E%D8%A8%D9%8E.html' },
      II: { gloss: 'to make (someone) write', trans: true,
            en: { past: 'made write', pp: 'made to write', pres3: 'makes write', ing: 'making write' } },
      III: { gloss: 'to correspond with', trans: true,
             en: { past: 'corresponded with', pp: 'corresponded with', pres3: 'corresponds with', ing: 'corresponding with' } },
      IV: { gloss: 'to dictate to', trans: true,
            en: { past: 'dictated to', pp: 'dictated to', pres3: 'dictates to', ing: 'dictating to' } },
      VI: { gloss: 'to write to one another', trans: false,
            en: { past: 'wrote to one another', pres3: 'write to one another', ing: 'writing to one another' } },
      VIII: { gloss: 'to register / to subscribe', trans: false,
              en: { past: 'registered', pres3: 'registers', ing: 'registering' } },
      X: { gloss: 'to ask (someone) to write', trans: true,
           en: { past: 'asked to write', pp: 'asked to write', pres3: 'asks to write', ing: 'asking to write' } },
    },
  },
  {
    root: ['ن', 'ص', 'ر'], type: 'salim',
    forms: {
      I: { bab: 'au', gloss: 'to help', masdar: 'نَصْر', trans: true,
           en: { past: 'helped', pp: 'helped', pres3: 'helps', ing: 'helping' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D8%B5%D9%8E%D8%B1%D9%8E.html' },
      III: { gloss: 'to support / to back', trans: true,
             en: { past: 'supported', pp: 'supported', pres3: 'supports', ing: 'supporting' } },
      VI: { gloss: 'to support one another', trans: false,
            en: { past: 'supported one another', pres3: 'support one another', ing: 'supporting one another' } },
      VIII: { gloss: 'to triumph / to be victorious', trans: false,
              en: { past: 'triumphed', pres3: 'triumphs', ing: 'triumphing' } },
      X: { gloss: 'to seek help from', trans: true,
           en: { past: 'sought help from', pp: 'asked for help', pres3: 'seeks help from', ing: 'seeking help from' } },
    },
  },
  {
    root: ['خ', 'ر', 'ج'], type: 'salim',
    forms: {
      I: { bab: 'au', gloss: 'to go out', masdar: 'خُرُوج', trans: false,
           en: { past: 'went out', pres3: 'goes out', ing: 'going out' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AE%D9%8E%D8%B1%D9%8E%D8%AC%D9%8E.html' },
      II: { gloss: 'to train / to graduate (someone)', trans: true,
            en: { past: 'trained', pp: 'trained', pres3: 'trains', ing: 'training' } },
      IV: { gloss: 'to expel / bring out', trans: true,
            en: { past: 'expelled', pp: 'expelled', pres3: 'expels', ing: 'expelling' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%AE%D9%92%D8%B1%D9%8E%D8%AC%D9%8E.html' },
      V: { gloss: 'to graduate', trans: false,
           en: { past: 'graduated', pres3: 'graduates', ing: 'graduating' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AE%D9%8E%D8%B1%D9%8E%D9%91%D8%AC%D9%8E.html' },
      X: { gloss: 'to extract', trans: true,
           en: { past: 'extracted', pp: 'extracted', pres3: 'extracts', ing: 'extracting' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D8%AE%D9%92%D8%B1%D9%8E%D8%AC%D9%8E.html' },
    },
  },
  {
    root: ['ن', 'ظ', 'ر'], type: 'salim',
    forms: {
      I: { bab: 'au', gloss: 'to look', masdar: 'نَظَر', trans: true,
           en: { past: 'looked', pp: 'looked at', pres3: 'looks', ing: 'looking' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%86%D9%8E%D8%B8%D9%8E%D8%B1%D9%8E.html' },
      III: { gloss: 'to debate with', trans: true,
             en: { past: 'debated with', pp: 'debated with', pres3: 'debates with', ing: 'debating with' } },
      VI: { gloss: 'to debate one another', trans: false,
            en: { past: 'debated one another', pres3: 'debate one another', ing: 'debating one another' } },
      VIII: { gloss: 'to wait for', trans: true,
              en: { past: 'waited for', pp: 'waited for', pres3: 'waits for', ing: 'waiting for' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D9%86%D9%92%D8%AA%D9%8E%D8%B8%D9%8E%D8%B1%D9%8E.html' },
    },
  },
  {
    root: ['ق', 'ت', 'ل'], type: 'salim',
    forms: {
      I: { bab: 'au', gloss: 'to kill', masdar: 'قَتْل', trans: true,
           en: { past: 'killed', pp: 'killed', pres3: 'kills', ing: 'killing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%82%D9%8E%D8%AA%D9%8E%D9%84%D9%8E.html' },
      II: { gloss: 'to massacre / to slaughter', trans: true,
            en: { past: 'massacred', pp: 'massacred', pres3: 'massacres', ing: 'massacring' } },
      III: { gloss: 'to fight', trans: true,
             en: { past: 'fought', pp: 'fought', pres3: 'fights', ing: 'fighting' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%82%D9%8E%D8%A7%D8%AA%D9%8E%D9%84%D9%8E.html' },
      VI: { gloss: 'to fight one another', trans: false,
            en: { past: 'fought one another', pres3: 'fight one another', ing: 'fighting one another' } },
      VIII: { gloss: 'to fight one another', trans: false,
              en: { past: 'fought one another', pres3: 'fight one another', ing: 'fighting one another' } },
      X: { gloss: 'to fight to the death', trans: false,
           en: { past: 'fought to the death', pres3: 'fights to the death', ing: 'fighting to the death' } },
    },
  },
  {
    root: ['ض', 'ر', 'ب'], type: 'salim',
    forms: {
      I: { bab: 'ai', gloss: 'to hit', masdar: 'ضَرْب', trans: true,
           en: { past: 'hit', pp: 'hit', pres3: 'hits', ing: 'hitting' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B6%D9%8E%D8%B1%D9%8E%D8%A8%D9%8E.html' },
      II: { gloss: 'to beat repeatedly', trans: true,
            en: { past: 'beat repeatedly', pp: 'beaten repeatedly', pres3: 'beats repeatedly', ing: 'beating repeatedly' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B6%D9%8E%D8%B1%D9%8E%D9%91%D8%A8%D9%8E.html' },
      III: { gloss: 'to speculate / to trade with', trans: true,
             en: { past: 'speculated', pp: 'speculated', pres3: 'speculates', ing: 'speculating' } },
      VI: { gloss: 'to conflict / to clash', trans: false,
            en: { past: 'conflicted', pres3: 'conflicts', ing: 'conflicting' } },
      VIII: { gloss: 'to be agitated / disturbed', trans: false,
              en: { past: 'was agitated', pres3: 'is agitated', ing: 'being agitated' } },
    },
  },
  {
    root: ['ج', 'ل', 'س'], type: 'salim',
    forms: {
      I: { bab: 'ai', gloss: 'to sit', masdar: 'جُلُوس', trans: false,
           en: { past: 'sat', pres3: 'sits', ing: 'sitting' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AC%D9%8E%D9%84%D9%8E%D8%B3%D9%8E.html' },
      III: { gloss: 'to sit with', trans: true,
             en: { past: 'sat with', pp: 'sat with', pres3: 'sits with', ing: 'sitting with' } },
      IV: { gloss: 'to seat (someone)', trans: true,
            en: { past: 'seated', pp: 'seated', pres3: 'seats', ing: 'seating' } },
    },
  },
  {
    root: ['ك', 'س', 'ر'], type: 'salim',
    forms: {
      I: { bab: 'ai', gloss: 'to break', masdar: 'كَسْر', trans: true,
           en: { past: 'broke', pp: 'broken', pres3: 'breaks', ing: 'breaking' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%83%D9%8E%D8%B3%D9%8E%D8%B1%D9%8E.html' },
      II: { gloss: 'to smash to pieces', trans: true,
            en: { past: 'smashed', pp: 'smashed', pres3: 'smashes', ing: 'smashing' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%83%D9%8E%D8%B3%D9%91%D9%8E%D8%B1%D9%8E.html' },
      V: { gloss: 'to be shattered', trans: false,
           en: { past: 'shattered', pres3: 'shatters', ing: 'shattering' } },
      VII: { gloss: 'to get broken', trans: false,
             en: { past: 'got broken', pres3: 'gets broken', ing: 'getting broken' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D9%86%D9%92%D9%83%D9%8E%D8%B3%D9%8E%D8%B1%D9%8E.html' },
    },
  },
  {
    root: ['غ', 'ف', 'ر'], type: 'salim',
    forms: {
      I: { bab: 'ai', gloss: 'to forgive', masdar: 'مَغْفِرَة', trans: true,
           en: { past: 'forgave', pp: 'forgiven', pres3: 'forgives', ing: 'forgiving' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%BA%D9%8E%D9%81%D9%8E%D8%B1%D9%8E.html' },
      X: { gloss: 'to seek forgiveness', trans: true,
           en: { past: 'sought forgiveness', pp: 'asked for forgiveness', pres3: 'seeks forgiveness', ing: 'seeking forgiveness' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D8%BA%D9%92%D9%81%D9%8E%D8%B1%D9%8E.html' },
    },
  },
  {
    root: ['ف', 'ت', 'ح'], type: 'salim',
    forms: {
      I: { bab: 'aa', gloss: 'to open', masdar: 'فَتْح', trans: true,
           en: { past: 'opened', pp: 'opened', pres3: 'opens', ing: 'opening' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%81%D9%8E%D8%AA%D9%8E%D8%AD%D9%8E.html' },
      III: { gloss: 'to broach (a subject) with', trans: true,
             en: { past: 'broached', pp: 'broached', pres3: 'broaches', ing: 'broaching' } },
      V: { gloss: 'to open up / to blossom', trans: false,
           en: { past: 'opened up', pres3: 'opens up', ing: 'opening up' } },
      VII: { gloss: 'to be opened', trans: false,
             en: { past: 'was opened', pres3: 'gets opened', ing: 'getting opened' } },
      VIII: { gloss: 'to inaugurate / to commence', trans: true,
              en: { past: 'inaugurated', pp: 'inaugurated', pres3: 'inaugurates', ing: 'inaugurating' } },
    },
  },
  {
    root: ['ج', 'م', 'ع'], type: 'salim',
    forms: {
      I: { bab: 'aa', gloss: 'to gather', masdar: 'جَمْع', trans: true,
           en: { past: 'gathered', pp: 'gathered', pres3: 'gathers', ing: 'gathering' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AC%D9%8E%D9%85%D9%8E%D8%B9%D9%8E.html' },
      II: { gloss: 'to collect / to assemble', trans: true,
            en: { past: 'collected', pp: 'collected', pres3: 'collects', ing: 'collecting' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AC%D9%8E%D9%85%D9%8E%D9%91%D8%B9%D9%8E.html' },
      IV: { gloss: 'to agree unanimously on', trans: true,
            en: { past: 'agreed on', pp: 'agreed on', pres3: 'agrees on', ing: 'agreeing on' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%AC%D9%92%D9%85%D9%8E%D8%B9%D9%8E.html' },
      V: { gloss: 'to gather together', trans: false,
           en: { past: 'gathered', pres3: 'gathers', ing: 'gathering' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AC%D9%8E%D9%85%D9%8E%D9%91%D8%B9%D9%8E.html' },
      VIII: { gloss: 'to assemble / meet', trans: false,
              en: { past: 'assembled', pres3: 'assembles', ing: 'assembling' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%AC%D9%92%D8%AA%D9%8E%D9%85%D9%8E%D8%B9%D9%8E.html' },
      X: { gloss: 'to summon / to muster', trans: true,
           en: { past: 'mustered', pp: 'mustered', pres3: 'musters', ing: 'mustering' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D8%AC%D9%92%D9%85%D9%8E%D8%B9%D9%8E.html' },
    },
  },
  {
    root: ['ظ', 'ه', 'ر'], type: 'salim',
    forms: {
      I: { bab: 'aa', gloss: 'to appear', masdar: 'ظُهُور', trans: true,
           en: { past: 'appeared', pres3: 'appears', ing: 'appearing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B8%D9%8E%D9%87%D9%8E%D8%B1%D9%8E.html' },
      II: { gloss: 'to endorse', trans: true,
            en: { past: 'endorsed', pp: 'endorsed', pres3: 'endorses', ing: 'endorsing' } },
      III: { gloss: 'to back / to side with', trans: true,
             en: { past: 'backed', pp: 'backed', pres3: 'backs', ing: 'backing' } },
      IV: { gloss: 'to reveal', trans: true,
            en: { past: 'revealed', pp: 'revealed', pres3: 'reveals', ing: 'revealing' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%B8%D9%92%D9%87%D9%8E%D8%B1%D9%8E.html' },
      VI: { gloss: 'to pretend / demonstrate', trans: false,
            en: { past: 'pretended', pres3: 'pretends', ing: 'pretending' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B8%D9%8E%D8%A7%D9%87%D9%8E%D8%B1%D9%8E.html' },
      X: { gloss: 'to memorize / to learn by heart', trans: true,
           en: { past: 'memorized', pp: 'memorized', pres3: 'memorizes', ing: 'memorizing' } },
    },
  },
  {
    root: ['س', 'م', 'ع'], type: 'salim',
    forms: {
      I: { bab: 'ia', gloss: 'to hear', masdar: 'سَمْع', trans: true,
           en: { past: 'heard', pp: 'heard', pres3: 'hears', ing: 'hearing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D9%85%D9%90%D8%B9%D9%8E.html' },
      IV: { gloss: 'to make (someone) hear', trans: true,
            en: { past: 'made hear', pp: 'made to hear', pres3: 'makes hear', ing: 'making hear' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%B3%D9%92%D9%85%D9%8E%D8%B9%D9%8E.html' },
      V: { gloss: 'to eavesdrop / to listen in', trans: false,
           en: { past: 'eavesdropped', pres3: 'eavesdrops', ing: 'eavesdropping' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B3%D9%8E%D9%85%D9%8E%D9%91%D8%B9%D9%8E.html' },
      VI: { gloss: 'to become widely known', trans: false,
            en: { past: 'became widely known', pres3: 'becomes widely known', ing: 'becoming widely known' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B3%D9%8E%D8%A7%D9%85%D9%8E%D8%B9%D9%8E.html' },
      VIII: { gloss: 'to listen', trans: true,
              en: { past: 'listened', pp: 'listened to', pres3: 'listens', ing: 'listening' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D9%85%D9%8E%D8%B9%D9%8E.html' },
    },
  },
  {
    root: ['ش', 'ر', 'ب'], type: 'salim',
    forms: {
      I: { bab: 'ia', gloss: 'to drink', masdar: 'شُرْب', trans: true,
           en: { past: 'drank', pp: 'drunk', pres3: 'drinks', ing: 'drinking' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B4%D9%8E%D8%B1%D9%90%D8%A8%D9%8E.html' },
      IV: { gloss: 'to give (someone) to drink', trans: true,
            en: { past: 'gave to drink', pp: 'given to drink', pres3: 'gives to drink', ing: 'giving to drink' } },
    },
  },
  {
    root: ['ع', 'ل', 'م'], type: 'salim',
    forms: {
      I: { bab: 'ia', gloss: 'to know', masdar: 'عِلْم', trans: true,
           en: { past: 'knew', pp: 'known', pres3: 'knows', ing: 'knowing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B9%D9%8E%D9%84%D9%90%D9%85%D9%8E.html' },
      II: { gloss: 'to teach', trans: true,
            en: { past: 'taught', pp: 'taught', pres3: 'teaches', ing: 'teaching' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B9%D9%8E%D9%84%D9%91%D9%8E%D9%85%D9%8E.html' },
      IV: { gloss: 'to inform / to notify', trans: true,
            en: { past: 'informed', pp: 'informed', pres3: 'informs', ing: 'informing' } },
      V: { gloss: 'to learn', trans: true,
           en: { past: 'learned', pp: 'learned', pres3: 'learns', ing: 'learning' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B9%D9%8E%D9%84%D9%91%D9%8E%D9%85%D9%8E.html' },
      VI: { gloss: 'to feign knowledge', trans: false,
            en: { past: 'feigned knowledge', pres3: 'feigns knowledge', ing: 'feigning knowledge' } },
      X: { gloss: 'to inquire', trans: true,
           en: { past: 'inquired', pp: 'inquired about', pres3: 'inquires', ing: 'inquiring' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D8%B9%D9%92%D9%84%D9%8E%D9%85%D9%8E.html' },
    },
  },
  {
    root: ['س', 'ل', 'م'], type: 'salim',
    forms: {
      I: { bab: 'ia', gloss: 'to be safe', masdar: 'سَلَامَة', trans: false,
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D9%84%D9%90%D9%85%D9%8E.html' },
      II: { gloss: 'to greet / hand over', trans: true,
            en: { past: 'greeted', pp: 'greeted', pres3: 'greets', ing: 'greeting' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D9%84%D9%91%D9%8E%D9%85%D9%8E.html' },
      III: { gloss: 'to make peace with', trans: true,
             en: { past: 'made peace with', pp: 'made peace with', pres3: 'makes peace with', ing: 'making peace with' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B3%D9%8E%D8%A7%D9%84%D9%8E%D9%85%D9%8E.html' },
      IV: { gloss: 'to submit (Islam)', trans: false,
            en: { past: 'submitted', pres3: 'submits', ing: 'submitting' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%B3%D9%92%D9%84%D9%8E%D9%85%D9%8E.html' },
      V: { gloss: 'to receive / to take delivery of', trans: true,
           en: { past: 'received', pp: 'received', pres3: 'receives', ing: 'receiving' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B3%D9%8E%D9%84%D9%8E%D9%91%D9%85%D9%8E.html' },
      VIII: { gloss: 'to receive / to take possession of', trans: true,
              en: { past: 'received', pp: 'received', pres3: 'receives', ing: 'receiving' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D9%84%D9%8E%D9%85%D9%8E.html' },
      X: { gloss: 'to surrender', trans: false,
           en: { past: 'surrendered', pres3: 'surrenders', ing: 'surrendering' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B3%D9%92%D8%AA%D9%8E%D8%B3%D9%92%D9%84%D9%8E%D9%85%D9%8E.html' },
    },
  },
  {
    root: ['ك', 'ر', 'م'], type: 'salim',
    forms: {
      I: { bab: 'uu', gloss: 'to be noble', masdar: 'كَرَم', trans: false,
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%83%D9%8E%D8%B1%D9%8F%D9%85%D9%8E.html' },
      II: { gloss: 'to honour', trans: true,
            en: { past: 'honoured', pp: 'honoured', pres3: 'honours', ing: 'honouring' } },
      III: { gloss: 'to vie in generosity with', trans: true,
             en: { past: 'vied with', pp: 'vied with', pres3: 'vies with', ing: 'vying with' } },
      IV: { gloss: 'to honor', trans: true,
            en: { past: 'honored', pp: 'honored', pres3: 'honors', ing: 'honoring' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D9%83%D9%92%D8%B1%D9%8E%D9%85%D9%8E.html' },
    },
  },
  {
    root: ['ق', 'د', 'م'], type: 'salim',
    forms: {
      I: { bab: 'uu', gloss: 'to be old / ancient', masdar: 'قِدَم', trans: false,
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%82%D9%8E%D8%AF%D9%8F%D9%85%D9%8E.html' },
      II: { gloss: 'to present / offer', trans: true,
            en: { past: 'presented', pp: 'presented', pres3: 'presents', ing: 'presenting' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D9%82%D9%8E%D8%AF%D9%91%D9%8E%D9%85%D9%8E.html' },
      IV: { gloss: 'to venture / to undertake boldly', trans: false,
            en: { past: 'ventured', pres3: 'ventures', ing: 'venturing' } },
      V: { gloss: 'to advance', trans: false,
           en: { past: 'advanced', pres3: 'advances', ing: 'advancing' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D9%82%D9%8E%D8%AF%D9%91%D9%8E%D9%85%D9%8E.html' },
      VI: { gloss: 'to grow old / to become outdated', trans: false,
            en: { past: 'grew old', pres3: 'grows old', ing: 'growing old' } },
      X: { gloss: 'to summon / to send for', trans: true,
           en: { past: 'summoned', pp: 'summoned', pres3: 'summons', ing: 'summoning' } },
    },
  },
  {
    root: ['ح', 'س', 'ب'], type: 'salim',
    forms: {
      // حَسِبَ يَحْسِبُ — bab ii, the famous irregular where a faʿila verb takes
      // a kasra in the muḍāriʿ instead of the expected fatḥa. The doublet
      // يَحْسَبُ (bab ia) is equally classical and is what the dictionaries
      // print first; يَحْسِبُ is kept because it is the reading a ṣarf student
      // is taught to notice. DECIDED 2026-09-20, not an oversight.
      I: { bab: 'ii', gloss: 'to deem / suppose', masdar: 'حُسْبَان', trans: true,
           en: { past: 'deemed', pp: 'deemed', pres3: 'deems', ing: 'deeming' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AD%D9%8E%D8%B3%D9%90%D8%A8%D9%8E.html' },
      III: { gloss: 'to call to account / to settle with', trans: true,
             en: { past: 'called to account', pp: 'called to account', pres3: 'calls to account', ing: 'calling to account' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AD%D9%8E%D8%A7%D8%B3%D9%8E%D8%A8%D9%8E.html' },
      V: { gloss: 'to be on guard', trans: false,
           en: { past: 'was on guard', pres3: 'is on guard', ing: 'being on guard' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AD%D9%8E%D8%B3%D9%8E%D9%91%D8%A8%D9%8E.html' },
      VI: { gloss: 'to settle accounts with one another', trans: false,
            en: { past: 'settled accounts', pres3: 'settle accounts', ing: 'settling accounts' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AD%D9%8E%D8%A7%D8%B3%D9%8E%D8%A8%D9%8E.html' },
      VIII: { gloss: 'to reckon / to seek reward from God', trans: true,
              en: { past: 'reckoned', pp: 'reckoned', pres3: 'reckons', ing: 'reckoning' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%AD%D9%92%D8%AA%D9%8E%D8%B3%D9%8E%D8%A8%D9%8E.html' },
    },
  },
  {
    root: ['ش', 'ر', 'ك'], type: 'salim',
    forms: {
      III: { gloss: 'to partner with', trans: true,
             en: { past: 'partnered with', pp: 'partnered with', pres3: 'partners with', ing: 'partnering with' },
             reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B4%D9%8E%D8%A7%D8%B1%D9%8E%D9%83%D9%8E.html' },
      IV: { gloss: 'to associate a partner with / to make a partner', trans: true,
            en: { past: 'associated', pp: 'associated', pres3: 'associates', ing: 'associating' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A3%D9%8E%D8%B4%D9%92%D8%B1%D9%8E%D9%83%D9%8E.html' },
      VI: { gloss: 'to partner with one another', trans: false,
            en: { past: 'partnered together', pres3: 'partner together', ing: 'partnering together' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%B4%D9%8E%D8%A7%D8%B1%D9%8E%D9%83%D9%8E.html' },
      VIII: { gloss: 'to participate', trans: false,
              en: { past: 'participated', pres3: 'participates', ing: 'participating' },
              reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B4%D9%92%D8%AA%D9%8E%D8%B1%D9%8E%D9%83%D9%8E.html' },
    },
  },
  {
    root: ['ح', 'م', 'ر'], type: 'salim',
    forms: {
      II: { gloss: 'to redden / to dye red', trans: true,
            en: { past: 'reddened', pp: 'reddened', pres3: 'reddens', ing: 'reddening' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AD%D9%8E%D9%85%D9%8E%D9%91%D8%B1%D9%8E.html' },
      IX: { gloss: 'to turn red', trans: false,
            en: { past: 'turned red', pres3: 'turns red', ing: 'turning red' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%AD%D9%92%D9%85%D9%8E%D8%B1%D9%91%D9%8E.html' },
    },
  },
  {
    root: ['ص', 'ف', 'ر'], type: 'salim',
    forms: {
      I: { bab: 'ia', gloss: 'to be empty / vacant', masdar: 'صَفَر', trans: false,
           en: { past: 'was empty', pres3: 'is empty', ing: 'being empty' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B5%D9%8E%D9%81%D9%90%D8%B1%D9%8E.html' },
      II: { gloss: 'to empty / to evacuate', trans: true,
            en: { past: 'emptied', pp: 'emptied', pres3: 'empties', ing: 'emptying' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%B5%D9%8E%D9%81%D9%8E%D9%91%D8%B1%D9%8E.html' },
      IX: { gloss: 'to turn yellow', trans: false,
            en: { past: 'turned yellow', pres3: 'turns yellow', ing: 'turning yellow' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%A7%D9%90%D8%B5%D9%92%D9%81%D9%8E%D8%B1%D9%91%D9%8E.html' },
    },
  },
  {
    root: ['ح', 'ك', 'م'], type: 'salim',
    forms: {
      I: { bab: 'au', gloss: 'to judge / to rule', masdar: 'حُكْم', trans: true,
           en: { past: 'judged', pp: 'judged', pres3: 'judges', ing: 'judging' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AD%D9%8E%D9%83%D9%8E%D9%85%D9%8E.html' },
      II: { gloss: 'to appoint as arbitrator', trans: true,
            en: { past: 'appointed as arbitrator', pp: 'appointed as arbitrator', pres3: 'appoints as arbitrator', ing: 'appointing as arbitrator' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AD%D9%8E%D9%83%D9%8E%D9%91%D9%85%D9%8E.html' },
      IV: { gloss: 'to perfect / to master', trans: true,
            en: { past: 'perfected', pp: 'perfected', pres3: 'perfects', ing: 'perfecting' } },
      V: { gloss: 'to control / to dominate', trans: false,
           en: { past: 'took control', pres3: 'takes control', ing: 'taking control' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AD%D9%8E%D9%83%D9%8E%D9%91%D9%85%D9%8E.html' },
      X: { gloss: 'to become firmly established', trans: false,
           en: { past: 'became established', pres3: 'becomes established', ing: 'becoming established' } },
    },
  },
  {
    root: ['ع', 'م', 'ل'], type: 'salim',
    forms: {
      I: { bab: 'ia', gloss: 'to work / to do', masdar: 'عَمَل', trans: true,
           en: { past: 'worked', pp: 'worked', pres3: 'works', ing: 'working' } },
      III: { gloss: 'to treat / to deal with', trans: true,
             en: { past: 'treated', pp: 'treated', pres3: 'treats', ing: 'treating' } },
      IV: { gloss: 'to put to work / to apply', trans: true,
            en: { past: 'applied', pp: 'applied', pres3: 'applies', ing: 'applying' } },
      VI: { gloss: 'to deal with one another', trans: false,
            en: { past: 'dealt with one another', pres3: 'deal with one another', ing: 'dealing with one another' } },
      X: { gloss: 'to use / to employ', trans: true,
           en: { past: 'used', pp: 'used', pres3: 'uses', ing: 'using' } },
    },
  },
  {
    root: ['د', 'ر', 'س'], type: 'salim',
    forms: {
      I: { bab: 'au', gloss: 'to study', masdar: 'دِرَاسَة', trans: true,
           en: { past: 'studied', pp: 'studied', pres3: 'studies', ing: 'studying' },
           reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AF%D9%8E%D8%B1%D9%8E%D8%B3%D9%8E.html' },
      II: { gloss: 'to teach', trans: true,
            en: { past: 'taught', pp: 'taught', pres3: 'teaches', ing: 'teaching' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AF%D9%8E%D8%B1%D9%8E%D9%91%D8%B3%D9%8E.html' },
      III: { gloss: 'to study with', trans: true,
             en: { past: 'studied with', pp: 'studied with', pres3: 'studies with', ing: 'studying with' } },
      VI: { gloss: 'to study together', trans: false,
            en: { past: 'studied together', pres3: 'study together', ing: 'studying together' },
            reverso: 'https://conjugator.reverso.net/conjugation-arabic-verb-%D8%AA%D9%8E%D8%AF%D9%8E%D8%A7%D8%B1%D9%8E%D8%B3%D9%8E.html' },
    },
  },
];
